/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bonus`; params?: Router.UnknownInputParams; } | { pathname: `/drivers_index`; params?: Router.UnknownInputParams; } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/subindex`; params?: Router.UnknownInputParams; } | { pathname: `/driver_profile`; params?: Router.UnknownInputParams; } | { pathname: `/passenger_profile`; params?: Router.UnknownInputParams; } | { pathname: `/shop_for_points`; params?: Router.UnknownInputParams; } | { pathname: `/purchases`; params?: Router.UnknownInputParams; } | { pathname: `/driver_purchases`; params?: Router.UnknownInputParams; } | { pathname: `/driver_shop`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/bonus`; params?: Router.UnknownOutputParams; } | { pathname: `/drivers_index`; params?: Router.UnknownOutputParams; } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/subindex`; params?: Router.UnknownOutputParams; } | { pathname: `/driver_profile`; params?: Router.UnknownOutputParams; } | { pathname: `/passenger_profile`; params?: Router.UnknownOutputParams; } | { pathname: `/shop_for_points`; params?: Router.UnknownOutputParams; } | { pathname: `/purchases`; params?: Router.UnknownOutputParams; } | { pathname: `/driver_purchases`; params?: Router.UnknownOutputParams; } | { pathname: `/driver_shop`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/bonus${`?${string}` | `#${string}` | ''}` | `/drivers_index${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/leaderboard${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/subindex${`?${string}` | `#${string}` | ''}` | `/driver_profile${`?${string}` | `#${string}` | ''}` | `/passenger_profile${`?${string}` | `#${string}` | ''}` | `/shop_for_points${`?${string}` | `#${string}` | ''}` | `/purchases${`?${string}` | `#${string}` | ''}` | `/driver_purchases${`?${string}` | `#${string}` | ''}` | `/driver_shop${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bonus`; params?: Router.UnknownInputParams; } | { pathname: `/drivers_index`; params?: Router.UnknownInputParams; } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/subindex`; params?: Router.UnknownInputParams; } | { pathname: `/driver_profile`; params?: Router.UnknownInputParams; } | { pathname: `/passenger_profile`; params?: Router.UnknownInputParams; } | { pathname: `/shop_for_points`; params?: Router.UnknownInputParams; } | { pathname: `/purchases`; params?: Router.UnknownInputParams; } | { pathname: `/driver_purchases`; params?: Router.UnknownInputParams; } | { pathname: `/driver_shop`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
